### ISSUE TITLE
Convert tables to other formatting

### ISSUE THREAD

**Issue by jimevans** [thechillquil/smdg-character-sheet#3]
The `character-sheet.html` file uses `<table>` elements to handle layout of the page. This is discouraged by Roll20, and by modern web design and layout techniques. The layout should be modified to use [CSS Flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox), or probably more appropriately, [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout).

**Comment by thechillquil** [comment]
Successfully converted all tables into HTML grid layout.
